FROM node:22-alpine

WORKDIR /app

# COPY client/package.json client/package-lock.json ./
COPY package.json package-lock.json ./

RUN npm install --ignore-scripts

# COPY client/ ./
COPY src ./src
COPY public ./public

EXPOSE 5173

USER node

CMD ["npm", "run", "dev"]

# NGINX stage
# FROM nginx:alpine
# COPY --from=builder /app/dist /usr/share/nginx/html
# COPY nginx/nginx.conf /etc/nginx/nginx.conf
# EXPOSE 80