stages:
  - build
  - deploy

variables:
  DOCKER_DRIVER: overlay2

before_script:
  - echo "CI/CD running on GitLab"

build-backend:
  stage: build
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH/backend:$CI_COMMIT_SHORT_SHA -f backend/Dockerfile .
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/backend:$CI_COMMIT_SHORT_SHA

build-frontend:
  stage: build
  script:
    - docker build -t registry.gitlab.com/$CI_PROJECT_PATH/frontend:$CI_COMMIT_SHORT_SHA -f frontend/Dockerfile .
    - docker push registry.gitlab.com/$CI_PROJECT_PATH/frontend:$CI_COMMIT_SHORT_SHA

deploy:
  stage: deploy
  before_script:
    - mkdir -p ~/.kube
    - echo "$KUBECONFIG_DATA" | base64 -d > ~/.kube/config
  script:
    - kubectl apply -f gitlab/k8s/namespace.yaml
    - kubectl apply -f gitlab/k8s/postgres-secret.yaml
    - kubectl apply -f gitlab/k8s/postgres.yaml
    - kubectl apply -f gitlab/k8s/backend.yaml
    - kubectl apply -f gitlab/k8s/frontend.yaml
    - kubectl apply -f gitlab/k8s/Ingress.yaml