apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: myapp
  labels:
    app: frontend
spec:
  selector:
    app: frontend      # ต้องตรงกับ Deployment template.metadata.labels.app
  ports:
    - name: http
      port: 80          # พอร์ตที่ expose ใน cluster
      targetPort: 5173  # พอร์ตที่ container ฟัง
      protocol: TCP
  type: ClusterIP
