# Secret ของ Postgres (ถ้ายังไม่ได้สร้าง)
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: app-authen
type: Opaque
data:
  POSTGRES_USER: cG9zdGdyZXM=      # postgres
  POSTGRES_PASSWORD: c2VjcmV0      # secret
  POSTGRES_DB: YXBwYXV0aGVu        # appauthen
---
# Deployment ของ backend
apiVersion: apps/v1
kind: Deployment
metadata:
  name: backend
  namespace: app-authen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: backend
  template:
    metadata:
      labels:
        app: backend
    spec:
      containers:
        - name: backend
          image: docker.io/wasu1304/backend:<commit-hash>
          # image: docker.io/wasu1304/backend:6b36a03
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 3000
          envFrom:
            - secretRef:
                name: app-secret
---
# Service ของ backend
apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: app-authen
spec:
  selector:
    app: backend
  ports:
    - port: 3000
      targetPort: 3000
