apiVersion: v1
kind: Service
metadata:
  name: backend
  namespace: myapp          # แก้ namespace ให้ตรงกับ Deployment
spec:
  selector:
    app: backend
  ports:
    - name: http
      port: 80
      targetPort: 5000
      protocol: TCP
  type: ClusterIP
