apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-main-config
  namespace: myapp
data:
  nginx.conf: |
    user  nginx;
    worker_processes  1;

    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;

    events {
        worker_connections 1024;
    }

    http {
        include       /etc/nginx/mime.types;
        default_type  application/octet-stream;

        sendfile        on;
        keepalive_timeout  65;

        include /etc/nginx/conf.d/*.conf;
    }
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-site-config
  namespace: myapp
data:
  default.conf: |
    upstream frontend {
        server frontend.myapp.svc.cluster.local:5173;
    }

    upstream backend {
        server backend.myapp.svc.cluster.local:3000;
    }

    server {
        listen 80;
        server_name localhost;

        location / {
          root /path/to/your/frontend/build; 
          index index.html;
          try_files $uri $uri/ /index.html;
      
          proxy_pass http://frontend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }

        location /api {
          proxy_pass http://backend;
          proxy_set_header Host $host;
          proxy_set_header X-Real-IP $remote_addr;
          proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
          proxy_set_header X-Forwarded-Proto $scheme;
        }
    }
