apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-authen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/wasu1304/frontend:5ab3ff7
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-authen
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
  env:
    - name: BACKEND_URL
      value: "http://backend:3000"
