apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  namespace: app-authen
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      containers:
        - name: frontend
          image: docker.io/wasu1304/frontend:a63c58d
          # image: docker.io/wasu1304/backend:<commit-hash>
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 80
          env:
            - name: VITE_API_URL
              value: "http://backend:3000"
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: app-authen
spec:
  type: NodePort
  selector:
    app: frontend
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30080
