apiVersion: apps/v1
kind: Deployment
metadata:
  name: myapp
  namespace: myapp     # ต้องมี namespace นี้สร้างไว้ก่อน
  labels:
    app: frontend
    component: web
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend   # ต้องตรงกับ template.metadata.labels.app
  template:
    metadata:
      labels:
        app: frontend
        component: web
    spec:
      containers:
      - name: frontend
        image: wasu1304/frontend:2
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 5173
          name: http
---
apiVersion: v1
kind: Service
metadata:
  name: frontend
  namespace: myapp
  labels:
    app: frontend
spec:
  selector:
    app: frontend      # ต้องตรงกับ Deployment template.metadata.labels.app
  ports:
    - name: http
      port: 80          # พอร์ตที่ expose ใน cluster
      targetPort: 5173  # พอร์ตที่ container ฟัง
      protocol: TCP
  type: ClusterIP
