apiVersion: v1
kind: Service
metadata:
  name: nginx
  namespace: myapp
spec:
  selector:
    app: nginx
  ports:
  - port: 80
    targetPort: 80
  type: NodePort   # เปลี่ยนเป็น LoadBalancer ได้ถ้าอยู่บน Cloud
