services:
  scanner:
    container_name: sonar-scanner
    platform: linux/amd64
    image: sonarsource/sonar-scanner-cli
    volumes:
      - .:/usr/src
    working_dir: /usr/src 
    command: sonar-scanner
    networks:
      - sonarqube-network

networks:
  sonarqube-network:
    driver: bridge
